random_facts = [
    "Bananas are berries, but strawberries are not.",
    "Sharks existed before trees.",
    "Octopuses have three hearts.",
    "Wombat poop is cube-shaped.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Sloths can hold their breath longer than dolphins.",
    "Honey never spoils — archaeologists have found 3000-year-old edible honey.",
    "Sharks don’t have bones — their skeletons are made of cartilage.",
    "The Eiffel Tower can grow more than 15 cm taller in the summer due to heat expansion.",
    "A day on Venus is longer than a year on Venus.",
    "Koalas have fingerprints that look almost identical to humans.",
    "The shortest war in history lasted 38 minutes (Anglo-Zanzibar War, 1896).",
    "Butterflies can taste with their feet.",
    "The first oranges were not orange — they were green.",
    "Pineapples take about 2 years to grow.",
    "Sharks are the only fish that can blink with both eyes.",
    "The human body has enough iron to make a small nail.",
    "A group of flamingos is called a 'flamboyance'.",
    "Your stomach gets a new lining every 3 to 4 days.",
    "There is a species of jellyfish that is biologically immortal.",
    "Cows have best friends and get stressed when separated.",
    "The moon has moonquakes, just like Earth has earthquakes.",
    "Water can boil and freeze at the same time in a process called 'triple point'.",
    "A group of crows is called a 'murder'.",
    "Sharks can live for more than 400 years (Greenland shark).",
    "Butterflies remember being caterpillars after metamorphosis.",
    "The fingerprints of a koala are so close to a human’s that they could confuse forensic investigators.",
    "There are more possible chess moves than atoms in the observable universe.",
    "Otters hold hands while they sleep so they don’t drift apart.",
    "Some cats are allergic to humans."
]
